### ISSUE TITLE
Establish Python project template used throughout repos.

### ISSUE THREAD

**Issue by yakutovicha** [nanotech-empa/general-issues#5]
Currently, there are multiple ways a Python project can be organized.

Here are the choices

- Python management tool: [setuptools](https://github.com/pypa/setuptools), [flit](https://github.com/pypa/flit), [hatch](https://github.com/pypa/hatch), [poetry](https://github.com/python-poetry/poetry). Current choice: [[flit](https://github.com/pypa/flit) for pure Python packages, [setuptools](https://github.com/pypa/setuptools) for everything else].
- Linters: [flake8](https://github.com/pycqa/flake8), [pylint](https://github.com/PyCQA/pylint). Current choice: [flake8]. Additional flake8-plugins:
    - [flake8-bugbear](https://pypi.org/project/flake8-bugbear/) for detecting bugs and potential design problems
    - [flake8-builtins](https://pypi.org/project/flake8-builtins/) for verifying that builtins are not used as variable names
    - [flake8-comprehensions](https://pypi.org/project/flake8-comprehensions/) for writing better and consistent comprehensions
    - [flake8-debugger](https://pypi.org/project/flake8-debugger/) for checking that there are no forgotten [breakpoints](https://docs.python.org/3/library/functions.html#breakpoint)
    - [flake8-eradicate](https://pypi.org/project/flake8-eradicate/) to avoid “dead” or commented code
    - [flake8-logging-format](https://github.com/globality-corp/flake8-logging-format) for consistent logging
    - [pep8-naming](https://pypi.org/project/pep8-naming/) for verifying that PEP8 naming conventions are followed
    - [tryceratops](https://pypi.org/project/tryceratops/) to avoid exception anti-patterns
- Type checking: [mypy](https://github.com/python/mypy). Current choice: [[mypy](https://github.com/python/mypy)]
    - [types-click-spinner](https://github.com/click-contrib/click-spinner)
    - [types-requests, types-tabulate, types-toml](https://github.com/python/typeshed)
- Auto-formatters:
    - [isort](https://pycqa.github.io/isort/) for sorting imports
    - [autoflake](https://github.com/PyCQA/autoflake) for removing unused imports
    - [black](https://github.com/psf/black) for formatting the rest of the code.
- Python auto-update:  [pyupgrade](https://github.com/asottile/pyupgrade) tool to automatically upgrade syntax for newer versions of the language.
- Release automation:  [bumpver](https://github.com/mbarkhau/bumpver). Current choice: [[bumpver](https://github.com/mbarkhau/bumpver)]
- Testing: [pytest](https://github.com/pytest-dev/pytest). Current choice: [pytest](https://github.com/pytest-dev/pytest).
- Documentation: _to complete_ 

Currently, I am working on a Python [cookie-cutter repository](https://github.com/yakutovicha/python-repository-template) to establish those. The issue is to be closed when all choices are made and the template repository reflects them.

The[ cookie-cutter repository](https://github.com/yakutovicha/python-repository-cookiecutter) will be largely based on https://github.com/woltapp/wolt-python-package-cookiecutter. I will also create an [accompanying template](https://github.com/yakutovicha/python-repository-template) similar to https://github.com/simonw/python-lib-template-repository. The idea is that the latter takes the cookie-cutter one, fills in the values and annihilates himself (see [this file](https://github.com/simonw/python-lib-template-repository/blob/main/.github/workflows/setup.yml) for the details).

**Comment by yakutovicha** [comment]
I believe a lot of inspiration can be taken from this [blog post](https://blog.wolt.com/engineering/2022/08/11/project-template-for-modern-python-packages/). Not only do they have a nice python-project template, but also they are able to perform bulk actions on **_already created_** repositories

**Comment by yakutovicha** [comment]
### `setuptools` vs `flint`. 

Flit is very simple to set up, it has built-in git integration (no need for the `MANIFEST` file anymore), and it reads version/description directly from the package `__init__.py`. So one doesn't need to set the version in multiple places.

So, it seems that for the pure python packages - flit is a better choice.

**Comment by yakutovicha** [comment]
## .pre-commit-config.yaml

I would propose using the following configuration:


```yaml
---
ci:
    autoupdat_schedule: quarterly

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: end-of-file-fixer
            exclude: ^.*data/
          - id: trailing-whitespace
            exclude: miscellaneous/structures/SiO2.xyz
          - id: check-yaml
          - id: check-added-large-files
    - repo: https://github.com/pycqa/isort
      rev: 5.12.0
      hooks:
          - id: isort
            args: [--profile, black, --filter-files]
    - repo: https://github.com/PyCQA/autoflake
      rev: v2.1.1
      hooks:
          - id: autoflake
    - repo: https://github.com/asottile/pyupgrade
      rev: v3.4.0
      hooks:
          - id: pyupgrade
            args: [--py38-plus]
    - repo: https://github.com/psf/black
      rev: 23.3.0
      hooks:
          - id: black
            language_version: python3 # Should be a command that runs python3.6+
    - repo: https://github.com/PyCQA/flake8
      rev: 6.0.0
      hooks:
          - id: flake8
            args: [--count, --show-source, --statistics]
            additional_dependencies:
                - flake8-bugbear
                - flake8-builtins
                - flake8-comprehensions
                - flake8-debugger
                - flake8-logging-format
                - pep8-naming
                - pyflakes
                - tryceratops
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.3.0
      hooks:
          - id: mypy
            additional_dependencies:
                - types-click-spinner
                - types-requests
                - types-tabulate
                - types-toml
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.3
      hooks:
          - id: yamlfmt
```

if the repo contains notebooks, it makes sense to add the following
```yaml
    - repo: https://github.com/kynan/nbstripout
      rev: 0.6.1
      hooks:
          - id: nbstripout

    - repo: https://github.com/nbQA-dev/nbQA
      rev: 1.7.0
      hooks:
          - id: nbqa-pyupgrade
            args: [--py38-plus]
          - id: nbqa-isort
            args: [--profile=black]
          - id: nbqa-black
```

if the repo contains `setup.cfg`, add the following
```yaml
    - repo: https://github.com/asottile/setup-cfg-fmt
      rev: v2.2.0
      hooks:
          - id: setup-cfg-fmt
```
